config/routes.rb
Todo::Application.routes.draw do
  resources :personal_statistics

  devise_for :users

  resources :users do
    resources :postits
  end

  resources :postits

  root :to => 'home#index'

end

app/models/personal_statistic.rb
class PersonalStatistic < ActiveRecord::Base
  belongs_to :user
  attr_accessible :item_array, :nr_of_dropzones, :user_id
end

app/models/postit.rb
class Postit < ActiveRecord::Base
  attr_accessible :content, :create_timestamp, :deadline_timestamp, :title, :status, :user_id

  belongs_to :user

end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :postit
  attr_accessible :status
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :postits
  has_one :personal_statistic

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   
  end
end

app/controllers/personal_statistics_controller.rb
class PersonalStatisticsController < ApplicationController

    before_filter :authenticate_user!

  # GET /personal_statistics
  # GET /personal_statistics.json
  def index
    @personal_statistics = PersonalStatistic.all
    # @dropzones = @personal_statistics.nr_of_dropzones

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @personal_statistics }
    end
  end

  # GET /personal_statistics/1
  # GET /personal_statistics/1.json
  def show
    @personal_statistic = PersonalStatistic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @personal_statistic }
    end
  end

  # GET /personal_statistics/new
  # GET /personal_statistics/new.json
  def new
    @personal_statistic = PersonalStatistic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @personal_statistic }
    end
  end

  # GET /personal_statistics/1/edit
  def edit
    @personal_statistic = PersonalStatistic.find(params[:id])
  end

  # POST /personal_statistics
  # POST /personal_statistics.json
  def create
    @personal_statistic = PersonalStatistic.new(params[:personal_statistic])
    @personal_statistic.user = current_user

    respond_to do |format|
      if @personal_statistic.save
        format.html { redirect_to @personal_statistic, notice: 'Personal statistic was successfully created.' }
        format.json { render json: @personal_statistic, status: :created, location: @personal_statistic }
      else
        format.html { render action: "new" }
        format.json { render json: @personal_statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /personal_statistics/1
  # PUT /personal_statistics/1.json
  def update
    @personal_statistic = PersonalStatistic.find(params[:id])

    respond_to do |format|
      if @personal_statistic.update_attributes(params[:personal_statistic])
        format.html { redirect_to @personal_statistic, notice: 'Personal statistic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @personal_statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_statistics/1
  # DELETE /personal_statistics/1.json
  def destroy
    @personal_statistic = PersonalStatistic.find(params[:id])
    @personal_statistic.destroy

    respond_to do |format|
      format.html { redirect_to personal_statistics_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/postits_controller.rb
class PostitsController < ApplicationController
  
  before_filter :authenticate_user!

  # GET /postits
  # GET /postits.json
  def index
    @postits = Postit.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @postits }
    end
  end

  # GET /postits/1
  # GET /postits/1.json
  def show
    @postit = Postit.find(params[:id])
    @user = @postit.user
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @postit }
    end
  end

  # GET /postits/new
  # GET /postits/new.json
  def new
    @postit = Postit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @postit }
    end
  end

  # GET /postits/1/edit
  def edit
    @postit = Postit.find(params[:id])
  end

  # POST /postits
  # POST /postits.json
  def create
    @postit = Postit.new(params[:postit])
    @postit.user = current_user

    # behövs den här raden? sätts tiden i databasen ändå?
    @postit.created_at = Time.now

    respond_to do |format|
      if @postit.save
        format.html { redirect_to @postit, notice: 'Postit was successfully created.' }
        format.json { render json: @postit, status: :created, location: @postit }
      else
        format.html { render action: "new" }
        format.json { render json: @postit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /postits/1
  # PUT /postits/1.json
  def update
    @postit = Postit.find(params[:id])

    respond_to do |format|
      if @postit.update_attributes(params[:postit])
        format.html { redirect_to @postit, notice: 'Postit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @postit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postits/1
  # DELETE /postits/1.json
  def destroy
    @postit = Postit.find(params[:id])
    @postit.destroy

    respond_to do |format|
      format.html { redirect_to postits_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Devise helpers
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personal_statistics_helper.rb
module PersonalStatisticsHelper
end

app/helpers/postits_helper.rb
module PostitsHelper
end

app/views/home/index.html.erb
<h1>My ToDo List</h1>

app/views/home/old_index.html.erb
<h1>My ToDo List</h1>
<%= link_to "My PosIts", postits_path %>

<section class="span4">
    <% if !user_signed_in? %>
      <%= render :partial => 'devise/sessions/new' %>
    <% else %>
      <p>Show me some crazy graphs! Apa</p>
      <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
    <% end %>
</section>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>

<ul class="nav">
    <li>
      <%= link_to 'Postits', postits_path %>
    <li>
    <li>
      <%= link_to 'My Bikes', personal_statistics_path %>
    <li>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <link href='http://fonts.googleapis.com/css?family=Coming+Soon' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/personal_statistics/_form.html.erb
<%= form_for(@personal_statistic) do |f| %>
  <% if @personal_statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personal_statistic.errors.count, "error") %> prohibited this personal_statistic from being saved:</h2>

      <ul>
      <% @personal_statistic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nr_of_dropzones %><br />
    <%= f.number_field :nr_of_dropzones %>
  </div>
  <div class="field">
    <%= f.label :item_array %><br />
    <%= f.text_field :item_array %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personal_statistics/edit.html.erb
<h1>Editing personal_statistic</h1>

<%= render 'form' %>

<%= link_to 'Show', @personal_statistic %> |
<%= link_to 'Back', personal_statistics_path %>

app/views/personal_statistics/index.html.erb
<%= provide(:nr_of_dropzones) %>

<h1>Listing My Bikes</h1>

<div id="postit" class="span4">
  <ul id="drag_items">
    <li draggable="true">Giant</li>
    <li draggable="true">Focus</li>
    <li draggable="true">Scott</li>
    <li draggable="true">KHS</li>
    <li draggable="true">Cervelo</li>
    <li draggable="true">Felt</li>
    <li draggable="true">Garyfisher</li>
    <li draggable="true">Trek</li>
  </ul>
</div>

<form id="choice_of_dropzones">
  <select>
    <option value="3">Tre</option>
    <option value="4">Fyra</option>
    <option value="5">Fem</option>
    <option value="6">Sex</option>
  </select>
  <input type="submit" value="Välj" />
</form>

<%= debug @personal_statistics %>

<div id="drop_zone_wrapper">

  <% $i = 0;
     $num = @personal_statistics.nr_of_dropzones.to_i;
     $drop_zone_id = "";
     
     until $i >= $num  do $drop_zone_id = "drop_zone_" + ($i + 1).to_s %>

  <div id="<%= $drop_zone_id %>" class="drop_zones span2"></div>

   <% $i +=1;
   end %>

</div>

<!--<input type="button" value="viewPickedItems" id="viewPickedItems" />-->

app/views/personal_statistics/new.html.erb
<h1>New personal_statistic</h1>

<%= render 'form' %>

<%= link_to 'Back', personal_statistics_path %>

app/views/personal_statistics/old.index.html.erb
<table>
  <tr>
    <th>Nr of dropzones</th>
    <th>Item array</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @personal_statistics.each do |personal_statistic| %>
  <tr>
    <td><%= personal_statistic.nr_of_dropzones %></td>
    <td><%= personal_statistic.item_array %></td>
    <td><%= personal_statistic.user %></td>
    <td><%= link_to 'Show', personal_statistic %></td>
    <td><%= link_to 'Edit', edit_personal_statistic_path(personal_statistic) %></td>
    <td><%= link_to 'Destroy', personal_statistic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Personal statistic', new_personal_statistic_path %>

app/views/personal_statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nr of dropzones:</b>
  <%= @personal_statistic.nr_of_dropzones %>
</p>

<p>
  <b>Item array:</b>
  <%= @personal_statistic.item_array %>
</p>

<p>
  <b>User:</b>
  <%= @personal_statistic.user.name %>
</p>


<%= link_to 'Edit', edit_personal_statistic_path(@personal_statistic) %> |
<%= link_to 'Back', personal_statistics_path %>

app/views/postits/_form.html.erb
<%= form_for(@postit) do |f| %>
  <% if @postit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@postit.errors.count, "error") %> prohibited this postit from being saved:</h2>

      <ul>
      <% @postit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, [['Ny','Ny'],['Pågår','Pågår'],['Klar','Klar']] %>
  </div>
  <div class="field">
    <%= f.label :deadline_timestamp %><br />
    <%= f.datetime_select(:deadline_timestamp, :default => 3.days.from_now) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/postits/edit.html.erb
<h1>Editing postit</h1>

<%= render 'form' %>

<%= link_to 'Show', @postit %> |
<%= link_to 'Back', postits_path %>

app/views/postits/index.html.erb
<h1>Listing postits</h1>

<table id="products" class="display">
  <thead>
  <tr>
    <th>Responsible</th>
    <th>Title</th>
    <th>Content</th>
    <th>Status</th>
    <th>Deadline</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @postits.each do |postit| %>
  <tr>
    <td><%= postit.user.name%></td>
    <td><%= postit.title %></td>
    <td><%= postit.content %></td>
    <td><%= postit.status %></td>
    <td><%= postit.deadline_timestamp.to_formatted_s(:short) %></td>
    <td><%= link_to 'Show', postit %></td>
    <td><%= link_to 'Edit', edit_postit_path(postit) %></td>
    <td><%= link_to postit, method: :delete, data: { confirm: 'Are you sure?' } do %>
      <span class="ui-icon ui-icon-trash"></span>
      <% end %>
    </td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Postit', new_postit_path %>

app/views/postits/new.html.erb
<h1>New postit</h1>

<%= render 'form' %>

<%= link_to 'Back', postits_path %>

app/views/postits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Creator:</b>
  <%= @user.name %>
</p>

<p>
  <b>Title:</b>
  <%= @postit.title %>
</p>

<p>
  <b>Content:</b>
  <%= @postit.content %>
</p>

<p>
  <b>Created at:</b>
  <%= @postit.created_at.to_s(:db) %>
</p>

<p>
  <b>Status:</b>
  <%= @postit.status %>
</p>

<p>
  <b>Deadline timestamp:</b>
  <%= @postit.deadline_timestamp.to_s(:db) %>
</p>


<%= link_to 'Edit', edit_postit_path(@postit) %> |
<%= link_to 'Back', postits_path %>

app/views/users/index.html.erb
<h1>Users</h1>